version: 1.2

currencyPrefix: '$'
currencySuffix: ''

currencyName: 'dollar'
currencyNamePlural: 'dollars'

shopNPCSkin: 1949474697
shopNPCName: Merchant
shopSellPercentage: 0.45 #The percentage of the buy price to sell items to the shop

enableCrates: true
dailyCrateCooldown: 86400000 #In milliseconds