version: 1.5

currencyPrefix: '$'
currencySuffix: ''

currencyName: 'dollar'
currencyNamePlural: 'dollars'

enableCrates: true
dailyCrateCooldown: 86400000 #24h in milliseconds

playerFirstJoinAmount: 100.0
startChunkAmounnt: 4
chunkPrice: 100.0
claimsEnabled: true