version: 1.3

currencyPrefix: '$'
currencySuffix: ''

currencyName: 'dollar'
currencyNamePlural: 'dollars'

shopNPCSkin: 1949474697
shopNPCName: Merchant
shopSellPercentage: 0.45 #The percentage of the buy price to sell items to the shop

enableCrates: true
dailyCrateCooldown: 86400000 #24h in milliseconds

playerFirstJoinAmount: 100.0
startChunkAmounnt: 4
chunkPrice: 100.0