name: SuperFactions
version: ${project.version}
main: com.github.imdabigboss.superfactions.SuperFactions
api-version: 1.17

softdepend:
  - Vault

commands:
  superfactions:
    description: The main Super Factions command
    usage: /superfactions <save/reload/info>
    permission: superfactions.admin
  balance:
    description: Get your balance
    usage: /balance
    permission: superfactions.normal
  money:
    description: Make transactions
    usage: /money
    permission: superfactions.normal
  shop:
    description: The shop command
    usage: /shop [setpos]
    permission: superfactions.normal
  dailycrate:
    description: Get a daily crate every set amount of time
    usage: /dailycrate
    permission: superfactions.normal
  opencrate:
    description: Open a previously claimed crate
    usage: /opencrate
    permission: superfactions.normal
  givecrate:
    description: Give a player a crate
    usage: /givecrate
    permission: superfactions.admin
  claim:
    description: Manage claimed chunks
    usage: /claim
    permission: superfactions.normal

permissions:
  superfactions.admin:
    default: op
    description: If a player has admin permissions
  superfactions.normal:
    default: true
    description: If a player has normal permissions
