name: SuperFactions
version: ${project.version}
main: com.github.imdabigboss.superfactions.SuperFactions
api-version: 1.16

softdepend:
  - Vault

commands:
  superfactions:
    description: The main Super Factions command
    usage: /superfactions <save/reload/info>
    permission: superfactions.admin
  balance:
    description: Get your balance
    usage: /balance
  money:
    description: Make transactions
    usage: /money
  shop:
    description: The shop command
    usage: /shop [setpos]
    permission: superfactions.admin
  dailycrate:
    description: Get a daily crate every set amount of time
    usage: /dailycrate
  opencrate:
    description: Open a previously claimed crate
    usage: /opencrate
  givecrate:
    description: Give a player a crate
    usage: /givecrate
    permission: superfactions.admin

permissions:
  superfactions.admin:
    default: op
    description: If a player has admin permissions
